// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"800","screenHeight":"600","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"Bgs_Sunlight","status":true,"description":"Sunlight effect","parameters":{">>>> Sun Properties <<<<<":"","Parallel":"true","Fixed":"true","Angle":"75","Position":"0.2","Brightness":"0.12","Density":"23","":"",">>>>>> Time System <<<<<<":"","Hour Variable Id":"-1","Minutes Variable Id":"-1","Sunrise Hour":"6","Sunset Hour":"18"}}
];
